### ISSUE TITLE
Could not find a version that satisfies the requirement ipykernel

### ISSUE THREAD

**Issue by kmilos** [Calysto/octave_kernel#117]
Unable to install in an Anaconda3 environment:

```
>pip install --use-wheel --no-index octave_kernel-0.27.2-py2.py3-none-any.whl
Processing octave_kernel-0.27.2-py2.py3-none-any.whl
Requirement already satisfied: metakernel>=0.20.7 in c:\anaconda3\envs\octave3\l
ib\site-packages (from octave-kernel==0.27.2)
Requirement already satisfied: jupyter-client>=4.3.0 in c:\anaconda3\envs\octave
3\lib\site-packages (from octave-kernel==0.27.2)
Collecting ipykernel (from octave-kernel==0.27.2)
  Could not find a version that satisfies the requirement ipykernel (from octave
-kernel==0.27.2) (from versions: )
No matching distribution found for ipykernel (from octave-kernel==0.27.2)
```

This is despite ipykernel being installed through conda, just like metakernel and jupyter-client:

```
>conda list ipykernel
# packages in environment at C:\Anaconda3\envs\octave3:
#
# Name                    Version                   Build  Channel
ipykernel                 4.8.0                    py36_0
```

(Trying w/ 0.27.2 since metakernel is stuck at 0.20.7 in conda currently...)

**Comment by blink1073** [comment]
Hi @kmilos, I'm not sure why pip isn't picking it up, but a newer version of `metakernel` is available in the `conda-forge` channel.   `conda install -c conda-forge octave_kernel`.

https://anaconda.org/conda-forge/metakernel

**Comment by kmilos** [comment]
Thanks @blink1073, didn't realize octave_kernel was available in conda-forge, all good now.

No idea why pip wasn't picking up ipykernel, here's the exception with -v just for info:

```
Exception information:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\octave3\lib\site-packages\pip\basecommand.py", line 21
5, in main
    status = self.run(options, args)
  File "C:\Anaconda3\envs\octave3\lib\site-packages\pip\commands\install.py", li
ne 335, in run
    wb.build(autobuilding=True)
  File "C:\Anaconda3\envs\octave3\lib\site-packages\pip\wheel.py", line 749, in
build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Anaconda3\envs\octave3\lib\site-packages\pip\req\req_set.py", line 38
0, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Anaconda3\envs\octave3\lib\site-packages\pip\req\req_set.py", line 55
4, in _prepare_file
    require_hashes
  File "C:\Anaconda3\envs\octave3\lib\site-packages\pip\req\req_install.py", lin
e 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Anaconda3\envs\octave3\lib\site-packages\pip\index.py", line 514, in
find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for ipykerne
l (from octave-kernel==0.27.2)
```

**Comment by blink1073** [comment]
What does `pip --version` show?

**Comment by kmilos** [comment]
```
>pip --version
pip 9.0.1 from C:\Anaconda3\envs\octave3\lib\site-packages (python 3.6)
```

**Comment by blink1073** [comment]
Wow, I wouldn't have expected that from `pip 9`.  I'm not quite sure then.  Closing because you were able to get it installed through `conda-forge`.  Cheers!
