### ISSUE TITLE
Octave kernel does not appear as an option in jupyter notebook, after installing octave_kernel

### ISSUE THREAD

**Issue by estebancolla** [Calysto/octave_kernel#118]
After

`pip install octave_kernel`

I get the following:

Requirement already satisfied: octave_kernel in ./Applications/anaconda/lib/python3.6/site-packages
Requirement already satisfied: ipykernel in ./Applications/anaconda/lib/python3.6/site-packages (from octave_kernel)
Requirement already satisfied: metakernel>=0.20.11 in ./Applications/anaconda/lib/python3.6/site-packages (from octave_kernel)
Requirement already satisfied: jupyter-client>=4.3.0 in ./Applications/anaconda/lib/python3.6/site-packages (from octave_kernel)
Requirement already satisfied: pexpect>=4.2 in ./Applications/anaconda/lib/python3.6/site-packages (from metakernel>=0.20.11->octave_kernel)

and after

`jupyter kernelspec list`

I get the following:

ir           /Users/estebancolla/Library/Jupyter/kernels/ir
julia-0.6    /Users/estebancolla/Library/Jupyter/kernels/julia-0.6
python3      /Users/estebancolla/Applications/anaconda/share/jupyter/kernels/python3

Does anybody know what am I doing wrong?

**Comment by blink1073** [comment]
Hi @estebancolla, can you please try uninstalling and then re-installing?  `pip uninstall -y octave_kernel && pip install octave_kernel`

**Comment by estebancolla** [comment]
After uninstalling and re-installing, I can now find Octave as one of the kernel options.

However, when I open a new notebook with Octave, the kernel dies after seconds, and I get the message below (Traceback ...etc)

Do I have to add to path or set "OCTAVE_EXECUTABLE" environment variable? If this is the solution, The path /Users/estebancolla/Applications/Octave.app would be enough?



Traceback (most recent call last):
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/octave_kernel/__main__.py", line 5, in <module>
    OctaveKernel.run_as_main()
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/metakernel/_metakernel.py", line 115, in run_as_main
    MetaKernelApp.launch_instance(kernel_class=cls)
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-120>", line 2, in initialize
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/metakernel/process_metakernel.py", line 54, in __init__
    self.wrapper = self.makeWrapper()
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/octave_kernel/kernel.py", line 94, in makeWrapper
    return self.octave_engine.repl
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/octave_kernel/kernel.py", line 88, in octave_engine
    logger=self.log)
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/octave_kernel/kernel.py", line 157, in __init__
    self.executable = self._get_executable()
  File "/Users/estebancolla/Applications/anaconda/lib/python3.6/site-packages/octave_kernel/kernel.py", line 432, in _get_executable
    raise OSError(msg)
OSError: Octave Executable not found, please add to path or set"OCTAVE_EXECUTABLE" environment variable

**Comment by blink1073** [comment]
Yep, adding `OCTAVE_EXECUTABLE=/Users/estebancolla/Applications/Octave.app` to `~/.bash_profile` should do the trick.

**Comment by estebancolla** [comment]
It did not work. I have to figure out which is the path to the Octave executable in OSX. There are folders within the Octave.App. It should be somewhere inside this folder. Thanks anyway!

**Comment by dsblank** [comment]
BYW, you can also set the executable by editing your `octave/kernel.json` file directly, like so:

```json
{
    "argv": [
	"/usr/bin/python3",
	"-m", "octave_kernel",
	"-f", "{connection_file}"
    ],
    "display_name": "Octave",
    "language": "octave",
    "mimetype": "text/x-octave",
    "name": "octave",
    "env": {
	"OCTAVE_EXECUTABLE": "/usr/bin/octave"
    }
}
```
