### ISSUE TITLE
Octave Kernel dies in Jupyter notebook (Win10)

### ISSUE THREAD

**Issue by Haru-Fujimura** [Calysto/octave_kernel#119]
So after installing Octave and using `jupyter notebook`, it seems that the octave kernel tries to connect, then dies immeadiately after. I had this issue with my win10 machine, but not on my UbuntuMate machine(17.04). 
I have set the OCTAVE_EXECUTABLE environment variable to the correct Octave\Octave4.2.1\bin folder. 
Is there anything else im missing?
Here is the terminal output:

```Traceback (most recent call last):
  File "C:\Users\Haru\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Haru\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\__main__.py", line 5, in <module>
    OctaveKernel.run_as_main()
  File "C:\Users\Haru\Miniconda3\lib\site-packages\metakernel\_metakernel.py", line 115, in run_as_main
    MetaKernelApp.launch_instance(kernel_class=cls)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\Haru\Miniconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\ipykernel\kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "C:\Users\Haru\Miniconda3\lib\site-packages\ipykernel\kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\Haru\Miniconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\metakernel\process_metakernel.py", line 54, in __init__
    self.wrapper = self.makeWrapper()
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 94, in makeWrapper
    return self.octave_engine.repl
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 88, in octave_engine
    logger=self.log)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 162, in __init__
    self._startup(plot_settings)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 300, in _startup
    self.eval(cmd % (cwd, self.repl.prompt_change_cmd), silent=True)
AttributeError: 'REPLWrapper' object has no attribute 'prompt_change_cmd'
[I 10:05:37.734 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
Traceback (most recent call last):
  File "C:\Users\Haru\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Haru\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\__main__.py", line 5, in <module>
    OctaveKernel.run_as_main()
  File "C:\Users\Haru\Miniconda3\lib\site-packages\metakernel\_metakernel.py", line 115, in run_as_main
    MetaKernelApp.launch_instance(kernel_class=cls)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-124>", line 2, in initialize
  File "C:\Users\Haru\Miniconda3\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\ipykernel\kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "C:\Users\Haru\Miniconda3\lib\site-packages\ipykernel\kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "C:\Users\Haru\Miniconda3\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\metakernel\process_metakernel.py", line 54, in __init__
    self.wrapper = self.makeWrapper()
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 94, in makeWrapper
    return self.octave_engine.repl
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 88, in octave_engine
    logger=self.log)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 162, in __init__
    self._startup(plot_settings)
  File "C:\Users\Haru\Miniconda3\lib\site-packages\octave_kernel\kernel.py", line 300, in _startup
    self.eval(cmd % (cwd, self.repl.prompt_change_cmd), silent=True)
AttributeError: 'REPLWrapper' object has no attribute 'prompt_change_cmd'
[I 10:05:40.854 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
Traceback (most recent call last):
  File "C:\Users\Haru\Miniconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Haru\Miniconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)```

**Comment by dsblank** [comment]
What versions of metakernel and octave_kernal do you have? You might try updating those to the latest versions.

**Comment by Haru-Fujimura** [comment]
octave_kernel is up to date. I have two versions of metakernel, one installed by PIP and the other by conda:

``metakernel                0.20.7           py36h260d091_0
metakernel                0.20.12                   <pip>``

**Comment by dsblank** [comment]
I think you want to make sure you are using the newer version. Can you delete/remove/uninstall the other?

**Comment by dsblank** [comment]
Thanks for the update. I'll update the README.
