### ISSUE TITLE
octave_kernel crash on macOS High Sierra (10.13.1)

### ISSUE THREAD

**Issue by jerryliu2005** [Calysto/octave_kernel#120]
Hello,

My jupyter notebook octave kernel keeps restarting due to time out. I tried your test code on both Python2.7 and Python3.6.2 and got the same errors of not getting the OctaveEngine back.

I have deleted my ~/.octave.rc and my Octave works fine on its own. Below is the traceback:

\>\>\> import os
\>\>\> print(os.environ['OCTAVE_EXECUTABLE'])
/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/bin/octave
\>\>\> from octave_kernel.kernel import OctaveEngine
\>\>\> e = OctaveEngine()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/octave_kernel/kernel.py", line 158, in __init__
    self.repl = self._create_repl()
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/octave_kernel/kernel.py", line 367, in _create_repl
    stdin_prompt_regex=STDIN_PROMPT_REGEX)
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/metakernel/replwrap.py", line 92, in __init__
    continuation_prompt_regex))
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/metakernel/replwrap.py", line 113, in set_prompt
    self.child.expect(prompt_regex)
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/pexpect/spawnbase.py", line 327, in expect
    timeout, searchwindowsize, async_)
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/pexpect/spawnbase.py", line 355, in expect_list
    return exp.expect_loop(timeout)
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/pexpect/expect.py", line 104, in expect_loop
    return self.timeout(e)
  File "/Users/liuxi/anaconda2/lib/python2.7/site-packages/pexpect/expect.py", line 68, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0x106910c90>
command: /Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/bin/octave
args: ['/Applications/Octave.app/Contents/Resources/usr/Cellar/octave/4.0.3/bin/octave', '--no-gui', '--interactive', '--quiet', '--no-init-file']
buffer (last 100 chars): u'>> '
before (last 100 chars): u'>> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 61567
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile("octave.*>")
\>\>\> e.eval('ones(3)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'e' is not defined

**Comment by blink1073** [comment]
Hi @jerryliu2005, does it work if you point to `octave-cli` instead of `octave`?

**Comment by jerryliu2005** [comment]
You are right.  octave-cli works the magic! Thanks!!

**Comment by blink1073** [comment]
Cheers!
