### ISSUE TITLE
Kernel dead: No module named octave_kernel on Ubuntu 

### ISSUE THREAD

**Issue by dkoen** [Calysto/octave_kernel#138]
```
jupyter kernelspec list
```

gives 

```
 Available kernels:
  octave     /home/captain/.local/share/jupyter/kernels/octave
  python2    /home/captain/.local/share/jupyter/kernels/python2
  python3    /usr/share/jupyter/kernels/python3
```

```
which octave
``` 

gives 

```
/usr/bin/octave
```
path to octave kernel is: 
```
~/.local/lib/python2.7/site-packages/octave_kernel 
```

installed by running 
```
sudo pip install octave_kernel
``` 

error is: 

```
Kernel started: 8f2dd88a-172b-4a17-b761-b1ac6466fb65
/usr/bin/python3: No module named octave_kernel
[I 14:00:03.559 NotebookApp] KernelRestarter: restarting kernel (1/5), new random ports
/usr/bin/python3: No module named octave_kernel
[I 14:00:06.567 NotebookApp] KernelRestarter: restarting kernel (2/5), new random ports
/usr/bin/python3: No module named octave_kernel
[I 14:00:09.577 NotebookApp] KernelRestarter: restarting kernel (3/5), new random ports
/usr/bin/python3: No module named octave_kernel
[W 14:00:10.638 NotebookApp] Timeout waiting for kernel_info reply from 8f2dd88a-172b-4a17-b761-b1ac6466fb65
[I 14:00:12.584 NotebookApp] KernelRestarter: restarting kernel (4/5), new random ports
WARNING:root:kernel 8f2dd88a-172b-4a17-b761-b1ac6466fb65 restarted
/usr/bin/python3: No module named octave_kernel
[W 14:00:15.594 NotebookApp] KernelRestarter: restart failed
[W 14:00:15.594 NotebookApp] Kernel 8f2dd88a-172b-4a17-b761-b1ac6466fb65 died, removing from map.
ERROR:root:kernel 8f2dd88a-172b-4a17-b761-b1ac6466fb65 restarted failed!
[W 14:00:15.624 NotebookApp] 410 DELETE /api/sessions/b861301c-9ee8-4275-9720-d607e9783c82 (127.0.0.1): Kernel deleted before session
[W 14:00:15.624 NotebookApp] Kernel deleted before session
[W 14:00:15.625 NotebookApp] 410 DELETE /api/sessions/b861301c-9ee8-4275-9720-d607e9783c82 (127.0.0.1) 2.80ms referer=http://localhost:8888/notebooks/Desktop/Jupyter%20Notebooks/homework_3_handout.ipynb
^C[I 14:00:22.346 NotebookApp] interrupted
Serving notebooks from local directory: /home/captain
0 active kernels
The Jupyter Notebook is running at:
http://localhost:8888/?token=2f6e34b38bf7beda0d6b5a0aaff4a1d9a2263b390b60b5c1
Shutdown this notebook server (y/[n])? No answer for 5s: resuming operation...
^C[I 14:03:13.182 NotebookApp] interrupted
Serving notebooks from local directory: /home/captain
0 active kernels
The Jupyter Notebook is running at:
http://localhost:8888/?token=2f6e34b38bf7beda0d6b5a0aaff4a1d9a2263b390b60b5c1
Shutdown this notebook server (y/[n])? ^C[C 14:03:14.655 NotebookApp] received signal 2, stopping
```

**Comment by dsblank** [comment]
Looks like you installed with python2, but are running under python3. Generally, you want to use the same Python to install and run. So:

```
/usr/bin/python3 -m pip install ocatve_kernel --user
```
You can look at `/home/captain/.local/share/jupyter/kernels/octave/kernel.json` to see if the correct Python is listed. If not, you can also:

```
/usr/bin/python3 -m octave_kernel install --user
```
and check again.

**Comment by dkoen** [comment]
Now I am getting the following error: 

```
Uncaught exception GET /api/kernels/9e8fd6ed-7370-40ae-8e2d-9099e3e0d29c/channels?session_id=53943B61B0A747B38490F8931D172D0E (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/api/kernels/9e8fd6ed-7370-40ae-8e2d-9099e3e0d29c/channels?session_id=53943B61B0A747B38490F8931D172D0E', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/captain/.local/lib/python3.6/site-packages/tornado/websocket.py", line 546, in _run_callback
        result = callback(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/notebook/services/kernels/handlers.py", line 258, in open
        super(ZMQChannelsHandler, self).open()
      File "/usr/lib/python3/dist-packages/notebook/base/zmqhandlers.py", line 168, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

**Comment by dsblank** [comment]
The Jupyter project just went through a major release, so things have recently changed. Some things you might try:

1. individually pip-updating certain packages:

```
/usr/bin/python3 -m pip install ocatve_kernel --user --upgrade
/usr/bin/python3 -m pip install jupyter --user --upgrade
```

2. pip has a way of upgrading all dependencies with `--upgrade-strategy eager`, so:

```
/usr/bin/python3 -m pip install ocatve_kernel --user --upgrade --upgrade-strategy eager
/usr/bin/python3 -m pip install jupyter --user --upgrade --upgrade-strategy eager
```

It can be the case that this type of upgrading can be dangerous. I have had to delete my entire ~/.local folder and start over.

**Comment by dkoen** [comment]
Thank you! The first solution worked!

**Comment by dsblank** [comment]
Good to hear; thanks for reporting back!
