### ISSUE TITLE
Timeout waiting for kernel_info reply

### ISSUE THREAD

**Issue by klonuo** [Calysto/octave_kernel#139]
I'm on Windows 10 with jupyter 4.4.0.

I installed this kernel and get no errors but timeout message in terminal.

![image](https://user-images.githubusercontent.com/361447/46943623-4f4a8b00-d070-11e8-951f-219c06ddb729.png)

Same happens with matlab kernel.

![image](https://user-images.githubusercontent.com/361447/46943639-5d001080-d070-11e8-80f4-150c16581887.png)

Any ideas what might be wrong?

**Comment by blink1073** [comment]
Hi @klonuo, can you please paste the output from `jupyter lab --debug` up to "timed out waiting for kernel" here as well?

**Comment by klonuo** [comment]
sure @blink1073:

```
[D 11:28:50.735 LabApp] Searching ['C:\\Users\\klo\\Downloads', 'C:\\Users\\klo\\.jupyter', 'c:\\python36\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[D 11:28:50.738 LabApp] Looking for jupyter_config in C:\ProgramData\jupyter
[D 11:28:50.749 LabApp] Looking for jupyter_config in c:\python36\etc\jupyter
[D 11:28:50.753 LabApp] Looking for jupyter_config in C:\Users\klo\.jupyter
[D 11:28:50.754 LabApp] Looking for jupyter_config in C:\Users\klo\Downloads
[D 11:28:50.760 LabApp] Looking for jupyter_notebook_config in C:\ProgramData\jupyter
[D 11:28:50.762 LabApp] Looking for jupyter_notebook_config in c:\python36\etc\jupyter
[D 11:28:50.763 LabApp] Looking for jupyter_notebook_config in C:\Users\klo\.jupyter
[D 11:28:50.787 LabApp] Loaded config file: C:\Users\klo\.jupyter\jupyter_notebook_config.py
[D 11:28:50.796 LabApp] Loaded config file: C:\Users\klo\.jupyter\jupyter_notebook_config.json
[D 11:28:50.797 LabApp] Looking for jupyter_notebook_config in C:\Users\klo\Downloads
[D 11:29:00.978 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\ProgramData\jupyter\jupyter_notebook_config.json
[D 11:29:00.979 LabApp] Paths used for configuration of jupyter_notebook_config:
        c:\python36\etc\jupyter\jupyter_notebook_config.d\jupyterlab-discovery.json
        c:\python36\etc\jupyter\jupyter_notebook_config.d\jupyterlab.json
        c:\python36\etc\jupyter\jupyter_notebook_config.json
[D 11:29:01.001 LabApp] Paths used for configuration of jupyter_notebook_config:
        C:\Users\klo\.jupyter\jupyter_notebook_config.json
[I 11:29:01.073 LabApp] JupyterLab extension loaded from c:\python36\lib\site-packages\jupyterlab
[I 11:29:01.073 LabApp] JupyterLab application directory is c:\python36\share\jupyter\lab
[W 11:29:01.187 LabApp] Error loading server extension jupyterlab_discovery
    Traceback (most recent call last):
      File "c:\python36\lib\site-packages\notebook\notebookapp.py", line 1576, in init_server_extensions
        func(self)
      File "c:\python36\lib\site-packages\jupyterlab_discovery\server_extension.py", line 18, in load_jupyter_server_extension
        from .handlers import (
      File "c:\python36\lib\site-packages\jupyterlab_discovery\handlers.py", line 25, in <module>
        from jupyterlab.commands import (
    ImportError: cannot import name '_read_package'
[W 11:29:01.333 LabApp] JupyterLab server extension not enabled, manually loading...
[I 11:29:01.370 LabApp] JupyterLab extension loaded from c:\python36\lib\site-packages\jupyterlab
[I 11:29:01.370 LabApp] JupyterLab application directory is c:\python36\share\jupyter\lab
[I 11:29:01.371 LabApp] Serving notebooks from local directory: c:\Users\klo\notebooks
[I 11:29:01.371 LabApp] The Jupyter Notebook is running at:
[I 11:29:01.371 LabApp] http://localhost:8888/
[I 11:29:01.372 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[D 11:29:01.764 LabApp] Using contents: services/contents
[D 11:29:01.918 LabApp] 304 GET /lab (::1) 170.40ms
[D 11:29:02.014 LabApp] Path vendors~main.bc6f588e79e9dd2e5d34.js served from c:\python36\share\jupyter\lab\static\vendors~main.bc6f588e79e9dd2e5d34.js
[D 11:29:02.016 LabApp] 304 GET /lab/static/vendors~main.bc6f588e79e9dd2e5d34.js (::1) 57.84ms
[D 11:29:02.018 LabApp] Path main.21998200f4edc9f73661.js served from c:\python36\share\jupyter\lab\static\main.21998200f4edc9f73661.js
[D 11:29:02.019 LabApp] 304 GET /lab/static/main.21998200f4edc9f73661.js (::1) 2.00ms
[D 11:29:03.496 LabApp] Found kernel javascript in C:\Users\klo\AppData\Roaming\jupyter\kernels
[D 11:29:03.622 LabApp] Found kernel matlab in c:\python36\share\jupyter\kernels
[D 11:29:03.623 LabApp] Found kernel octave in c:\python36\share\jupyter\kernels
[D 11:29:03.624 LabApp] Found kernel python3 in c:\python36\share\jupyter\kernels
[D 11:29:05.038 LabApp] Found kernel dot in C:\ProgramData\jupyter\kernels
[D 11:29:05.039 LabApp] Found kernel jython in C:\ProgramData\jupyter\kernels
[D 11:29:05.039 LabApp] Found kernel python2 in C:\ProgramData\jupyter\kernels
[D 11:29:05.040 LabApp] Found kernel sparql in C:\ProgramData\jupyter\kernels
[D 11:29:05.312 LabApp] 200 GET /api/kernelspecs?1539682143270 (::1) 2034.56ms
[D 11:29:05.443 LabApp] 200 GET /lab/api/settings/@jupyterlab/application-extension:sidebar?1539682143338 (::1) 128.65ms
[D 11:29:05.523 LabApp] 200 GET /lab/api/settings/@jupyterlab/shortcuts-extension:plugin?1539682143339 (::1) 75.79ms
[D 11:29:05.580 LabApp] 200 GET /lab/api/settings/@jupyterlab/docmanager-extension:plugin?1539682143343 (::1) 54.80ms
[D 11:29:05.620 LabApp] 200 GET /lab/api/settings/@jupyterlab/apputils-extension:themes?1539682143345 (::1) 37.89ms
[D 11:29:05.993 LabApp] 200 GET /api/contents/?content=1&1539682143794 (::1) 371.04ms
[D 11:29:06.047 LabApp] 200 GET /lab/api/settings/@jupyterlab/extensionmanager-extension:plugin?1539682143808 (::1) 48.87ms
[D 11:29:06.103 LabApp] 200 GET /lab/api/settings/@jupyterlab/google-drive:drive?1539682143831 (::1) 54.85ms
[D 11:29:06.106 LabApp] Using contents: services/contents
[D 11:29:06.293 LabApp] Path base/images/favicon.ico served from c:\python36\lib\site-packages\notebook\static\base\images\favicon.ico
[D 11:29:06.335 LabApp] Path components/jquery-ui/themes/smoothness/jquery-ui.min.css served from c:\python36\lib\site-packages\notebook\static\components\jquery-ui\themes\smoothness\jquery-ui.min.css
[D 11:29:06.367 LabApp] Path components/jquery-typeahead/dist/jquery.typeahead.min.css served from c:\python36\lib\site-packages\notebook\static\components\jquery-typeahead\dist\jquery.typeahead.min.css
[D 11:29:06.416 LabApp] Path style/style.min.css served from c:\python36\lib\site-packages\notebook\static\style\style.min.css
[D 11:29:06.425 LabApp] Path components/es6-promise/promise.min.js served from c:\python36\lib\site-packages\notebook\static\components\es6-promise\promise.min.js
[D 11:29:06.620 LabApp] Path components/preact/index.js served from c:\python36\lib\site-packages\notebook\static\components\preact\index.js
[D 11:29:06.724 LabApp] Path components/proptypes/index.js served from c:\python36\lib\site-packages\notebook\static\components\proptypes\index.js
[D 11:29:06.839 LabApp] Path components/preact-compat/index.js served from c:\python36\lib\site-packages\notebook\static\components\preact-compat\index.js
[D 11:29:06.917 LabApp] Path components/requirejs/require.js served from c:\python36\lib\site-packages\notebook\static\components\requirejs\require.js
[D 11:29:06.937 LabApp] Path base/images/logo.png served from c:\python36\lib\site-packages\notebook\static\base\images\logo.png
[W 11:29:06.941 LabApp] 404 GET /github?1539682143837 (::1) 835.68ms referer=http://localhost:8888/lab
[D 11:29:06.988 LabApp] Path @jupyterlab\theme-light-extension\index.css served from c:\python36\share\jupyter\lab\themes\@jupyterlab\theme-light-extension\index.css
[D 11:29:06.990 LabApp] 304 GET /lab/api/themes/@jupyterlab/theme-light-extension/index.css (::1) 32.96ms
[D 11:29:07.480 LabApp] 200 GET /lab/api/settings/@jupyterlab/github:drive?1539682143841 (::1) 487.01ms
[D 11:29:07.487 LabApp] 200 GET /lab/api/settings/@jupyterlab/google-drive:drive?1539682143842 (::1) 4.99ms
[D 11:29:07.498 LabApp] 200 GET /lab/api/settings/@jupyterlab/google-drive:drive?1539682143843 (::1) 6.98ms
[D 11:29:07.503 LabApp] 200 GET /api/terminals?1539682143274 (::1) 1.99ms
[W 11:29:07.567 LabApp] Failed validating settings (@jupyterlab/notebook-extension:tracker): False is not of type 'string'

    Failed validating 'type' in schema['properties']['codeCellConfig']['properties']['lineWrap']:
        {'enum': ['off', 'on', 'wordWrapColumn', 'bounded'], 'type': 'string'}

    On instance['codeCellConfig']['lineWrap']:
        False
[D 11:29:07.572 LabApp] 200 GET /lab/api/settings/@jupyterlab/notebook-extension:tracker?1539682143849 (::1) 65.81ms
[I 11:29:09.373 LabApp] Node v8.12.0

[W 11:29:09.454 LabApp] The extension "jupyterlab_discovery" is outdated.

[D 11:29:12.903 LabApp] 200 GET /api/nbconvert?1539682143851 (::1) 5322.77ms
[W 11:29:13.121 LabApp] Failed validating settings (@jupyterlab/fileeditor-extension:plugin): True is not of type 'string'

    Failed validating 'type' in schema['properties']['editorConfig']['properties']['lineWrap']:
        {'enum': ['off', 'on', 'wordWrapColumn', 'bounded'], 'type': 'string'}

    On instance['editorConfig']['lineWrap']:
        True
[D 11:29:13.129 LabApp] 200 GET /lab/api/settings/@jupyterlab/fileeditor-extension:plugin?1539682143855 (::1) 222.41ms
[D 11:29:13.297 LabApp] 200 GET /api/nbconvert?1539682143888 (::1) 160.61ms
[D 11:29:13.334 LabApp] 200 GET /lab/api/settings/@jupyterlab/codemirror-extension:commands?1539682143893 (::1) 34.90ms
[D 11:29:13.393 LabApp] 200 GET /api/sessions?1539682143900 (::1) 56.86ms
[D 11:29:13.397 LabApp] 200 GET /api/sessions?1539682145318 (::1) 1.99ms
[D 11:29:13.546 LabApp] 200 GET /api/sessions?1539682153275 (::1) 1.03ms
[D 11:29:13.550 LabApp] 200 GET /api/terminals?1539682153277 (::1) 1.99ms
[D 11:29:13.593 LabApp] Fetching URL: https://registry.npmjs.org/@jupyter-widgets%2Fjupyterlab-manager
[D 11:29:13.627 LabApp] 200 GET /lab/api/settings/nbdime-jupyterlab:plugin?1539682143891 (::1) 71.80ms
[I 11:29:13.629 LabApp] Build is up to date
[D 11:29:13.633 LabApp] 200 GET /lab/api/build?1539682143782 (::1) 6682.40ms
[D 11:29:13.832 LabApp] 200 GET /lab/api/workspaces/lab?1539682153653 (::1) 16.95ms
[D 11:29:13.839 LabApp] Path b1efea7ab3eceaa05d36173c0bcd54fe.png served from c:\python36\share\jupyter\lab\static\b1efea7ab3eceaa05d36173c0bcd54fe.png
[D 11:29:13.842 LabApp] 304 GET /lab/static/b1efea7ab3eceaa05d36173c0bcd54fe.png (::1) 7.03ms
[D 11:29:13.884 LabApp] 200 GET /api/contents/?content=1&1539682153800 (::1) 37.90ms
[D 11:29:13.898 LabApp] 204 PUT /lab/api/workspaces/lab?1539682153851 (::1) 6.97ms
[W 11:29:13.901 LabApp] 404 GET /api/contents/Untitled3.ipynb?content=0&1539682153843 (::1): No such file or directory: Untitled3.ipynb
[W 11:29:13.901 LabApp] No such file or directory: Untitled3.ipynb
[W 11:29:13.902 LabApp] 404 GET /api/contents/Untitled3.ipynb?content=0&1539682153843 (::1) 1.99ms referer=http://localhost:8888/lab
[D 11:29:13.970 LabApp] Fetching URL: https://registry.npmjs.org/@jupyterlab%2Fgit
[D 11:29:13.983 LabApp] Serving kernel resource from: c:\python36\share\jupyter\kernels\python3
[D 11:29:14.039 LabApp] 304 GET /kernelspecs/python3/logo-64x64.png (::1) 57.84ms
[D 11:29:14.050 LabApp] Serving kernel resource from: C:\ProgramData\jupyter\kernels\sparql
[D 11:29:14.100 LabApp] 304 GET /kernelspecs/sparql/logo-64x64.png (::1) 55.85ms
[D 11:29:14.109 LabApp] Serving kernel resource from: c:\python36\share\jupyter\kernels\matlab
[D 11:29:14.183 LabApp] 304 GET /kernelspecs/matlab/logo-64x64.png (::1) 81.33ms
[D 11:29:14.192 LabApp] Serving kernel resource from: C:\ProgramData\jupyter\kernels\dot
[D 11:29:14.366 LabApp] 304 GET /kernelspecs/dot/logo-64x64.png (::1) 181.92ms
[D 11:29:14.393 LabApp] Serving kernel resource from: C:\ProgramData\jupyter\kernels\python2
[D 11:29:14.495 LabApp] 304 GET /kernelspecs/python2/logo-64x64.png (::1) 125.65ms
[D 11:29:14.498 LabApp] Serving kernel resource from: C:\Users\klo\AppData\Roaming\jupyter\kernels\javascript
[D 11:29:14.576 LabApp] 304 GET /kernelspecs/javascript/logo-64x64.png (::1) 80.11ms
[D 11:29:14.589 LabApp] Serving kernel resource from: C:\ProgramData\jupyter\kernels\jython
[D 11:29:14.657 LabApp] 304 GET /kernelspecs/jython/logo-64x64.png (::1) 77.78ms
[D 11:29:14.669 LabApp] Serving kernel resource from: c:\python36\share\jupyter\kernels\octave
[D 11:29:14.721 LabApp] 304 GET /kernelspecs/octave/logo-64x64.png (::1) 56.85ms
[D 11:29:14.816 LabApp] 204 PUT /lab/api/workspaces/lab?1539682154782 (::1) 17.93ms
[D 11:29:15.690 LabApp] Fetching URL: https://registry.npmjs.org/@jupyterlab%2Fgithub
[D 11:29:17.240 LabApp] Fetching URL: https://registry.npmjs.org/@jupyterlab%2Fgoogle-drive
[D 11:29:18.810 LabApp] Fetching URL: https://registry.npmjs.org/@jupyterlab%2Ftoc
[I 11:29:19.975 LabApp] Creating new notebook in /
[D 11:29:19.993 LabApp] Saving c:\Users\klo\notebooks\Untitled1.ipynb
[D 11:29:20.352 LabApp] Fetching URL: https://registry.npmjs.org/@jupyterlab%2Fxkcd-extension
[D 11:29:20.508 LabApp] 201 POST /api/contents/?1539682159970 (::1) 533.57ms
[D 11:29:20.521 LabApp] 200 GET /api/contents/Untitled1.ipynb?content=0&1539682160512 (::1) 1.99ms
[D 11:29:20.550 LabApp] 200 GET /api/contents/?content=1&1539682160513 (::1) 26.95ms
[D 11:29:20.575 LabApp] Using contents: services/contents
[W 11:29:20.578 LabApp] 404 POST /nbdime/api/isgit?1539682160569 (::1) 3.99ms referer=http://localhost:8888/lab
[D 11:29:20.764 LabApp] 200 GET /api/contents/Untitled1.ipynb?type=notebook&content=1&1539682160631 (::1) 130.65ms
[D 11:29:20.808 LabApp] Path af7ae505a9eed503f8b8e6982036873e.woff2 served from c:\python36\share\jupyter\lab\static\af7ae505a9eed503f8b8e6982036873e.woff2
[D 11:29:20.811 LabApp] 304 GET /lab/static/af7ae505a9eed503f8b8e6982036873e.woff2 (::1) 38.91ms
[D 11:29:20.851 LabApp] Path components\MathJax\MathJax.js served from c:\python36\lib\site-packages\notebook\static\components\MathJax\MathJax.js
[D 11:29:20.859 LabApp] 304 GET /static/components/MathJax/MathJax.js?config=TeX-AMS-MML_HTMLorMML-full,Safe&amp;delayStartupUntil=configured%22%20charset=%22utf-8%22 (::1) 44.89ms
[D 11:29:20.875 LabApp] 200 GET /api/contents/Untitled1.ipynb/checkpoints?1539682160808 (::1) 5.97ms
[D 11:29:20.887 LabApp] 200 GET /api/contents/Untitled1.ipynb/checkpoints?1539682160796 (::1) 4.03ms
[D 11:29:20.896 LabApp] 200 GET /api/contents/Untitled1.ipynb/checkpoints?1539682160792 (::1) 5.00ms
[D 11:29:21.188 LabApp] Starting kernel: ['c:\\python36\\python.exe', '-m', 'octave_kernel', '-f', 'C:\\Users\\klo\\AppData\\Roaming\\jupyter\\runtime\\kernel-d3fc9ebb-f729-4517-9921-385ed3dbcaaa.json']
[D 11:29:21.231 LabApp] Connecting to: tcp://127.0.0.1:62399
[D 11:29:21.267 LabApp] Connecting to: tcp://127.0.0.1:62397
[I 11:29:21.273 LabApp] Kernel started: d3fc9ebb-f729-4517-9921-385ed3dbcaaa
[D 11:29:21.274 LabApp] Kernel args: {'kernel_name': 'octave', 'cwd': 'c:\\Users\\klo\\notebooks'}
[D 11:29:21.282 LabApp] 201 POST /api/sessions?1539682160938 (::1) 341.46ms
[D 11:29:21.290 LabApp] Path components\MathJax\config\TeX-AMS-MML_HTMLorMML-full.js served from c:\python36\lib\site-packages\notebook\static\components\MathJax\config\TeX-AMS-MML_HTMLorMML-full.js
[D 11:29:21.293 LabApp] 304 GET /static/components/MathJax/config/TeX-AMS-MML_HTMLorMML-full.js?V=2.7.5 (::1) 6.00ms
[D 11:29:21.307 LabApp] Initializing websocket connection /api/kernels/d3fc9ebb-f729-4517-9921-385ed3dbcaaa/channels
[D 11:29:21.311 LabApp] Requesting kernel info from d3fc9ebb-f729-4517-9921-385ed3dbcaaa
[D 11:29:21.312 LabApp] Connecting to: tcp://127.0.0.1:62396
[D 11:29:21.490 LabApp] Path components\MathJax\config\Safe.js served from c:\python36\lib\site-packages\notebook\static\components\MathJax\config\Safe.js
[D 11:29:21.492 LabApp] 304 GET /static/components/MathJax/config/Safe.js?V=2.7.5 (::1) 3.00ms
[D 11:29:21.554 LabApp] 204 PUT /lab/api/workspaces/lab?1539682161540 (::1) 9.97ms
[D 11:29:21.636 LabApp] Path components\MathJax\extensions\Safe.js served from c:\python36\lib\site-packages\notebook\static\components\MathJax\extensions\Safe.js
[D 11:29:21.638 LabApp] 304 GET /static/components/MathJax/extensions/Safe.js?V=2.7.5 (::1) 50.87ms
[D 11:29:21.641 LabApp] Initializing websocket connection /api/kernels/d3fc9ebb-f729-4517-9921-385ed3dbcaaa/channels
[D 11:29:21.650 LabApp] Waiting for pending kernel_info request
[D 11:29:21.800 LabApp] Path components\MathJax\jax\output\HTML-CSS\fonts\STIX-Web\fontdata.js served from c:\python36\lib\site-packages\notebook\static\components\MathJax\jax\output\HTML-CSS\fonts\STIX-Web\fontdata.js
[D 11:29:21.803 LabApp] 304 GET /static/components/MathJax/jax/output/HTML-CSS/fonts/STIX-Web/fontdata.js?V=2.7.5 (::1) 22.94ms
[D 11:29:21.893 LabApp] Fetching URL: https://registry.npmjs.org/jupyterlab_discovery
[D 11:29:22.152 LabApp] Fetching URL: https://registry.npmjs.org/nbdime-jupyterlab
[D 11:29:22.423 LabApp] Fetching URL: https://registry.npmjs.org/@ryantam626%2Fjupyterlab_sublime
[D 11:29:23.280 LabApp] 200 GET /api/sessions?1539682163275 (::1) 1.00ms
[D 11:29:23.285 LabApp] 200 GET /api/terminals?1539682163276 (::1) 1.99ms
[D 11:29:30.835 LabApp] 200 GET /api/contents/?content=1&1539682170798 (::1) 27.93ms
[D 11:29:33.287 LabApp] 200 GET /api/sessions?1539682173275 (::1) 3.99ms
[D 11:29:33.292 LabApp] 200 GET /api/terminals?1539682173276 (::1) 1.00ms
[D 11:29:40.836 LabApp] 200 GET /api/contents/?content=1&1539682180800 (::1) 24.94ms
[D 11:29:43.290 LabApp] 200 GET /api/sessions?1539682183274 (::1) 2.99ms
[D 11:29:43.296 LabApp] 200 GET /api/terminals?1539682183276 (::1) 1.99ms
[D 11:29:50.287 LabApp] 200 GET /lab/api/extensions?1539682146066 (::1) 36887.76ms
[D 11:29:50.289 LabApp] 200 GET /lab/api/extensions?1539682153647 (::1) 36638.40ms
[D 11:29:51.841 LabApp] 200 GET /api/contents/?content=1&1539682191799 (::1) 29.88ms
[D 11:29:53.288 LabApp] 200 GET /api/sessions?1539682193274 (::1) 2.99ms
[D 11:29:53.293 LabApp] 200 GET /api/terminals?1539682193278 (::1) 1.00ms
[D 11:30:02.836 LabApp] 200 GET /api/contents/?content=1&1539682202799 (::1) 25.92ms
[D 11:30:03.288 LabApp] 200 GET /api/sessions?1539682203275 (::1) 2.99ms
[D 11:30:03.294 LabApp] 200 GET /api/terminals?1539682203279 (::1) 2.00ms
[D 11:30:04.279 LabApp] Found kernel javascript in C:\Users\klo\AppData\Roaming\jupyter\kernels
[D 11:30:04.280 LabApp] Found kernel matlab in c:\python36\share\jupyter\kernels
[D 11:30:04.283 LabApp] Found kernel octave in c:\python36\share\jupyter\kernels
[D 11:30:04.290 LabApp] Found kernel python3 in c:\python36\share\jupyter\kernels
[D 11:30:04.298 LabApp] Found kernel dot in C:\ProgramData\jupyter\kernels
[D 11:30:04.303 LabApp] Found kernel jython in C:\ProgramData\jupyter\kernels
[D 11:30:04.304 LabApp] Found kernel python2 in C:\ProgramData\jupyter\kernels
[D 11:30:04.305 LabApp] Found kernel sparql in C:\ProgramData\jupyter\kernels
[D 11:30:04.327 LabApp] 200 GET /api/kernelspecs?1539682204276 (::1) 48.88ms
[D 11:30:12.841 LabApp] 200 GET /api/contents/?content=1&1539682212800 (::1) 28.92ms
[D 11:30:13.289 LabApp] 200 GET /api/sessions?1539682213276 (::1) 3.03ms
[D 11:30:13.295 LabApp] 200 GET /api/terminals?1539682213278 (::1) 2.00ms
[W 11:30:21.326 LabApp] Timeout waiting for kernel_info reply from d3fc9ebb-f729-4517-9921-385ed3dbcaaa
```

**Comment by blink1073** [comment]
Hi @klonuo, can you please try the following:

- Run `pip uninstall jupyterlab_discovery` (this is built into JupyterLab now).
- Launch `jupyter lab --no-browser`
- Copy the url and add `?reset` added to the end in the browser tab
- Open an new octave kernel notebook in the launcher

**Comment by klonuo** [comment]
Thanks @blink1073 however it's still the same:

```
C:\Users\klo>jupyter lab --no-browser
[I 12:50:01.007 LabApp] JupyterLab extension loaded from c:\python36\lib\site-packages\jupyterlab
[I 12:50:01.007 LabApp] JupyterLab application directory is c:\python36\share\jupyter\lab
[W 12:50:01.007 LabApp] JupyterLab server extension not enabled, manually loading...
[I 12:50:01.022 LabApp] JupyterLab extension loaded from c:\python36\lib\site-packages\jupyterlab
[I 12:50:01.022 LabApp] JupyterLab application directory is c:\python36\share\jupyter\lab
[I 12:50:01.038 LabApp] Serving notebooks from local directory: c:\Users\klo\notebooks
[I 12:50:01.038 LabApp] The Jupyter Notebook is running at:
[I 12:50:01.038 LabApp] http://localhost:8888/
[I 12:50:01.038 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 12:50:42.302 LabApp] Node v8.12.0

[W 12:50:42.674 LabApp] 404 GET /github?1539773441577 (::1) 938.49ms referer=http://localhost:8888/lab?reset
[W 12:50:43.094 LabApp] Failed validating settings (@jupyterlab/notebook-extension:tracker): False is not of type 'string'

    Failed validating 'type' in schema['properties']['codeCellConfig']['properties']['lineWrap']:
        {'enum': ['off', 'on', 'wordWrapColumn', 'bounded'], 'type': 'string'}

    On instance['codeCellConfig']['lineWrap']:
        False
[W 12:50:45.084 LabApp] Failed validating settings (@jupyterlab/fileeditor-extension:plugin): True is not of type 'string'

    Failed validating 'type' in schema['properties']['editorConfig']['properties']['lineWrap']:
        {'enum': ['off', 'on', 'wordWrapColumn', 'bounded'], 'type': 'string'}

    On instance['editorConfig']['lineWrap']:
        True
[I 12:50:45.514 LabApp] Build is up to date
[I 12:50:49.618 LabApp] Creating new notebook in /
[W 12:50:50.476 LabApp] 404 POST /nbdime/api/isgit?1539773450470 (::1) 2.00ms referer=http://localhost:8888/lab
[I 12:50:51.136 LabApp] Kernel started: 54a5dc1a-f4b5-414d-a821-11fc8239ba97
[W 12:51:51.192 LabApp] Timeout waiting for kernel_info reply from 54a5dc1a-f4b5-414d-a821-11fc8239ba97
```

**Comment by blink1073** [comment]
Does the kernel start when you launch `jupyter notebook`?

**Comment by klonuo** [comment]
No, that problem is just with jython kernel

**Comment by klonuo** [comment]
I was referring to the issue opened in jupyterlab repo - only jython kernel starts in notebook but not in lab.
Octave and matlab kernel fail to start in both notebook and lab.

**Comment by blink1073** [comment]
Do you have any antivirus software running that might be blocking websocket traffic?

**Comment by klonuo** [comment]
Only Windows defender, that comes bundled with system, but other kernels (except for jython) work fine

**Comment by blink1073** [comment]
Hmm, it could be that the process is taking too long to start up, this is a configurable trait::

https://github.com/jupyter/notebook/blob/4135e3ffe7df627cd9f264f600b2990145af17f6/notebook/services/kernels/kernelmanager.py#L99

Should be settable as `c.MappingKernelManager.kernel_info_timeout` in `jupyter_notebook_config.py`.

**Comment by klonuo** [comment]
It was some setting in ~/.jupyter folder.
After renaming the folder octave starts.
I'll try to detect which setting was the problem tomorrow.

**Comment by klonuo** [comment]
The problem seems to be with `jupyter_notebook_config.py`, and this setting:

```
c.NotebookApp.notebook_dir = 'c:/Users/klo/notebooks'
```

If I commentthis setting octave/matlab kernels start successfully.

**Comment by dsblank** [comment]
@klonuo Thanks for tracking that down; much appreciated!

**Comment by klonuo** [comment]
sure, thanks to you guys

**Comment by klonuo** [comment]
I'm able to start from that folder, if I comment `notebook_dir` setting.
I also tried changing notebook_dir to other location, i.e. `c:\temp` and it cannot start.

**Comment by blink1073** [comment]
Weird, I'll try the same when I am on my dev machine again.

**Comment by blink1073** [comment]
Wow, I was able to reproduce on Windows 10 but not on Linux Mint.   I'll have to do some more digging this weekend.

**Comment by blink1073** [comment]
@klonuo, I finally got around to looking at this.  It appears to be working now with the latest version, can you please `pip install -U octave_kernel` and try again?

**Comment by diallobakary4** [comment]
I am having the saving with jupyter-lab and notebook. Everything worked fine up to recently.
I deactivated the firewall and ad blocker on the browser, also tried another browser. 
I changed configurations in 
/home/user/.jupyter/jupyter_notebook_config.py
increasing c.MappingKernelManager.kernel_info_timeout to 180
and also trying home directory for c.NotebookApp.notebook_dir without success, still the same behavior "c.MappingKernelManager.kernel_info_timeout"

**Comment by blink1073** [comment]
Hi @diallobakary4, what OS are you using?  What is the output of `python -m octave_kernel.check`?

**Comment by diallobakary4** [comment]
The OS is Linux (CentOS) but I am using an octave kernel but a python. I am reinstalling a new conda env now.
