### ISSUE TITLE
octave-cli not found?

### ISSUE THREAD

**Issue by yellow-circle** [Calysto/octave_kernel#163]
Hi, I am using windows 10 and I installed the octave kernel using pip.
I have added the octave-cli executable to the path variable as shown (or well, I think that's how you're meant to do it.)
![Capture](https://user-images.githubusercontent.com/50559893/68730212-218f9700-0620-11ea-869c-c64271593c06.PNG)

I get this error message below when I try to start an octave kernel on jupyterlab.

```
[I 13:58:35.640 LabApp] The port 8888 is already in use, trying another port.
[I 13:58:35.641 LabApp] The port 8889 is already in use, trying another port.
[I 13:58:35.690 LabApp] Loading IPython parallel extension
[I 13:58:35.715 LabApp] JupyterLab extension loaded from C:\Users\_Kookie\Anaconda3\lib\site-packages\jupyterlab
[I 13:58:35.715 LabApp] JupyterLab application directory is C:\Users\_Kookie\Anaconda3\share\jupyter\lab
[I 13:58:35.735 LabApp] Serving notebooks from local directory: C:\Users\_Kookie
[I 13:58:35.735 LabApp] The Jupyter Notebook is running at:
[I 13:58:35.735 LabApp] http://localhost:8890/?token=c5791448a1880cf2a1e7ee3c3e9351458a9ad32e3ab413d9
[I 13:58:35.735 LabApp] or http://127.0.0.1:8890/?token=c5791448a1880cf2a1e7ee3c3e9351458a9ad32e3ab413d9
[I 13:58:35.735 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:58:35.795 LabApp] 

To access the notebook, open this file in a browser:
file:///C:/Users/_Kookie/AppData/Roaming/jupyter/runtime/nbserver-1120-open.html
Or copy and paste one of these URLs:
http://localhost:8890/?token=c5791448a1880cf2a1e7ee3c3e9351458a9ad32e3ab413d9
or http://127.0.0.1:8890/?token=c5791448a1880cf2a1e7ee3c3e9351458a9ad32e3ab413d9
[W 13:58:38.914 LabApp] Could not determine jupyterlab build status without nodejs
[I 13:58:40.502 LabApp] New terminal with automatic name: 1
[I 13:58:41.370 LabApp] New terminal with automatic name: 2
TermSocket.open: 1
TermSocket.open: Opened 1
TermSocket.open: 2
TermSocket.open: Opened 2
[I 13:58:42.744 LabApp] Kernel started: 4e1d98ab-9d8f-4b80-8ae3-64eae688d1c7
[I 13:58:42.810 LabApp] Kernel started: 82a38cb6-7d55-4ed5-8e32-f86ae78dba19
[I 13:58:42.832 LabApp] Kernel started: 37e14a16-a4ef-4f52-9169-b91071e4f4be
[MetaKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
yield gen.maybe_future(handler(stream, idents, msg))
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 654, in kernel_info_request
content.update(self.kernel_info)
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 647, in kernel_info
'language_info': self.language_info,
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 78, in language_info
'version': self.language_version,
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 69, in language_version
ver = self.octave_engine.eval('version', silent=True)
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 96, in octave_engine
logger=self.log)
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 170, in __init__
self.executable = self._get_executable()
File "C:\Users\_Kookie\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 457, in _get_executable
raise OSError('octave-cli not found, please see README')
OSError: octave-cli not found, please see README
```

How do I fix this?

**Comment by blink1073** [comment]
Hi @yellow-circle, is there an `octave-cli.exe` in that `mingw\bin` folder?

**Comment by yellow-circle** [comment]
Yes there is. Also I managed to solve the issue: I had to restart Anaconda, then it worked.
