### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vivepate\\AppData\\Local\\Temp\\_MEI104322\\octave_kernel\\kernel.json'

### ISSUE THREAD

**Issue by vivekpatel99** [Calysto/octave_kernel#165]
I am trying to generate exe file using pyinstaller.  My python script is working completely fine but my new generated exe file via pyinstaller is showing me the following error.
Can you please help me to solve following error? thank you in advanced.

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    from oct2py import octave
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\vivepate\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\oct2py\__init__.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\vivepate\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\oct2py\core.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\vivepate\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\octave_kernel\__init__.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\vivepate\appdata\local\continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\octave_kernel\kernel.py", line 52, in <module>
  File "site-packages\octave_kernel\kernel.py", line 58, in OctaveKernel
  File "site-packages\octave_kernel\kernel.py", line 46, in get_kernel_json
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\vivepate\\AppData\\Local\\Temp\\_MEI104322\\octave_kernel\\kernel.json'
[8952] Failed to execute script main

**Comment by blink1073** [comment]
Hi @vivekpatel99, I'm not sure how that would happen.  Looking at the [code](https://github.com/Calysto/octave_kernel/blob/master/octave_kernel/kernel.py#L43), I'd expect it to look in `site-packages\octave_kernel`, unless PyInstaller is somehow affecting `__file__`.

**Comment by msiemionCalistapw** [comment]
I ran into a similar error... mine is FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\msiemion\\AppData\\Local\\Temp\\_MEI232162\\splink\\files\\chart_defs\\profile_data.json'

has anyone figured out the reasoning for this issue yet?
