### ISSUE TITLE
[WinError 193] %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by mpiorczynski** [Calysto/octave_kernel#189]
(base) D:\Python\PPPD>jupyter kernelspec list
Available kernels:
octave D:\anaconda3\share\jupyter\kernels\octave
python3 D:\anaconda3\share\jupyter\kernels\python3

(base) D:\Python\PPPD>python -m octave_kernel.check
Octave kernel v0.32.0
Metakernel v0.27.5
Python v3.8.3 (default, Jul 2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)]
Python path: D:\anaconda3\python.exe

Connecting to Octave...
Can't load 'D:\anaconda3\lib\site-packages\metakernel\magics\shell_magic.py': error: <pexpect.popen_spawn.PopenSpawn object at 0x0000002143D51640>
searcher: searcher_re:
0: re.compile('\r\n')
1: EOF
<pexpect.popen_spawn.PopenSpawn object at 0x0000002143D51640>
searcher: searcher_re:
0: re.compile('\r\n')
1: EOF
Octave connection established
[WinError 193] %1 is not a valid Win32 application

I already have Octave installed on my Windows laptop and I have set OCTAVE_EXECUTABLE to octave-cli in the environment variables.
How to fix it?

**Comment by leo-smi** [comment]
I have the same problem on windows 7 64x
![image](https://user-images.githubusercontent.com/20663547/112359330-ec816300-8caf-11eb-8277-0efa9c068c93.png)

**Comment by AnonymoZ** [comment]
The same problem. Until @Calysto decides to fix.. my full traceback is as such:

My links first:
OCTAVE_EXECUTABLE
C:\Program Files\GNU Octave\Octave-6.3.0\mingw64\bin\octave-cli.exe
Path
C:\Program Files\GNU Octave\Octave-6.3.0\mingw64\bin

> Traceback (most recent call last):
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\ipykernel\kernelbase.py", line 352, in dispatch_shell
>     await result
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\ipykernel\kernelbase.py", line 760, in kernel_info_request
>     content.update(self.kernel_info)
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\ipykernel\kernelbase.py", line 753, in kernel_info
>     'language_info': self.language_info,
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\octave_kernel\kernel.py", line 78, in language_info
>     'version': self.language_version,
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\octave_kernel\kernel.py", line 69, in language_version
>     ver = self.octave_engine.eval('version', silent=True)
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\octave_kernel\kernel.py", line 96, in octave_engine
>     logger=self.log)
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\octave_kernel\kernel.py", line 173, in __init__
>     self.repl = self._create_repl()
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\octave_kernel\kernel.py", line 392, in _create_repl
>     force_prompt_on_continuation=True)
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\metakernel\replwrap.py", line 63, in __init__
>     encoding="utf-8")
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\metakernel\pexpect.py", line 32, in spawn
>     encoding=encoding, codec_errors=codec_errors)
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\site-packages\pexpect\popen_spawn.py", line 53, in __init__
>     self.proc = subprocess.Popen(cmd, **kwargs)
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "c:\users\oosman\appdata\local\programs\python\python37\lib\subprocess.py", line 1178, in _execute_child
>     startupinfo)

**OSError: [WinError 193] %1 is not a valid Win32 application**
