### ISSUE TITLE
KeyError 'metadata' on completions

### ISSUE THREAD

**Issue by Genora51** [Calysto/octave_kernel#190]
Running `jupyter console --kernel octave` crashes when attempting to get code-completions with tab.

The following error is produced:
```
Shutting down kernel
Task exception was never retrieved
future: <Task finished name='Task-2' coro=<ZMQTerminalInteractiveShell.interact() done, defined at /Users/geno/miniconda3/lib/python3.8/site-packages/jupyter_console/ptshell.py:635> exception=KeyError('metadata')>
Traceback (most recent call last):
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/jupyter_console/ptshell.py", line 640, in interact
    code = await self.prompt_for_code()
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/jupyter_console/ptshell.py", line 583, in prompt_for_code
    text = await self.pt_cli.prompt_async(default=default)
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1195, in prompt_async
    return await self.app.run_async(set_exception_handler=set_exception_handler)
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 815, in run_async
    return await _run_async2()
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 797, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 906, in cancel_and_wait_for_background_tasks
    await task
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1738, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 271, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 198, in get_completions_async
    for item in self.get_completions(document, complete_event):
  File "/Users/geno/miniconda3/lib/python3.8/site-packages/jupyter_console/ptshell.py", line 152, in get_completions
    meta = content["metadata"]
KeyError: 'metadata'
```

**Comment by dsblank** [comment]
That should be fairly easy to fix, I would think. Thanks for reporting!

**Comment by QuLogic** [comment]
This is presumably causing the following crash in tests with 0.33.1:
```
======================================================================
ERROR: test_completion (__main__.OctaveKernelTests) (text='acos')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/jupyter_kernel_test/__init__.py", line 143, in test_completion
    validate_message(reply, 'complete_reply', msg_id)
  File "/usr/lib/python3.10/site-packages/jupyter_kernel_test/msgspec_v5.py", line 141, in validate_message
    content_vdor.validate(msg['content'])
  File "/usr/lib/python3.10/site-packages/jsonschema/validators.py", line 353, in validate
    raise error
jsonschema.exceptions.ValidationError: 'metadata' is a required property

Failed validating 'required' in schema:
    {'$schema': 'http://json-schema.org/draft-04/schema#',
     'additionalProperties': True,
     'description': 'complete_reply message contents schema',
     'properties': {'cursor_end': {'type': 'number'},
                    'cursor_start': {'type': 'number'},
                    'matches': {'items': {'type': 'string'},
                                'type': 'array'},
                    'metadata': {'type': 'object'},
                    'status': {'const': 'ok'}},
     'required': ['cursor_end',
                  'cursor_start',
                  'matches',
                  'metadata',
                  'status'],
     'type': 'object'}

On instance:
    {'cursor_end': 4,
     'cursor_start': 0,
     'matches': ['acos', 'acosd', 'acosh'],
     'status': 'ok'}

```

**Comment by blink1073** [comment]
I'm working on fixing this in `metakernel`: https://github.com/Calysto/metakernel/pull/238
