### ISSUE TITLE
Kernel restart loop (anaconda python 2.7.10, OS X 10.7, Octave 4.0.0)

### ISSUE THREAD

**Issue by brianbaquiran** [Calysto/octave_kernel#22]
Creating a new Octave notebook produces a "Kernel has died" error message and the following log output (http://pastebin.com/4T2VVCyn): 
```
[W 12:52:04.310 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20151015125046 (::1) 20.35ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=octave_kernel
[I 12:52:04.570 NotebookApp] Kernel started: 4338bcfd-e5d2-4c53-8387-6ee2002ec9f2
//anaconda/envs/kaggle/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
//anaconda/envs/kaggle/lib/python2.7/site-packages/metakernel/_metakernel.py:23: UserWarning: Cannot load module  so metakernel will not be available to IPython/jupyter.
  warnings.warn("Cannot load module {name} so metakernel will not be available to IPython/jupyter.".format(name=getattr(e, 'name', '')))
IPython: an enhanced interactive Python shell.

Subcommands
-----------

Subcommands are launched as `ipython-kernel cmd [args]`. For information on
using subcommand 'cmd', do: `ipython-kernel cmd -h`.

install
    Install the IPython kernel

Options
-------

Arguments that take values are actually convenience aliases to full
Configurables, whose aliases are listed on the help line. For more information
on full configurables, see '--help-all'.

--no-autoindent
    Turn off autoindenting.
--deep-reload
    **Deprecated** Enable deep (recursive) reloading by default. IPython can use the
    deep_reload module which reloads changes in modules recursively (it
    replaces the reload() function, so you don't need to change anything to
    use it). deep_reload() forces a full reload of modules whose code may
    have changed, which the default reload() function does not.  When
    deep_reload is off, IPython will use the normal reload(), but
    deep_reload will still be available as dreload(). This feature is off
    by default [which means that you have both normal reload() and
    dreload()].
--secure
    Use HMAC digests for authentication of messages.
    Setting this flag will generate a new UUID to use as the HMAC key.
--pylab
    Pre-load matplotlib and numpy for interactive use with
    the default matplotlib backend.
--matplotlib
    Configure matplotlib for interactive use with
    the default matplotlib backend.
--autoindent
    Turn on autoindenting.
--automagic
    Turn on the auto calling of magic commands. Type %%magic at the
    IPython  prompt  for  more information.
--no-secure
    Don't authenticate messages.
--no-deep-reload
    Disable deep (recursive) reloading by default.
--no-stdout
    redirect stdout to the null device
--no-automagic
    Turn off the auto calling of magic commands.
--nosep
    Eliminate all spacing between prompts.
--pprint
    Enable auto pretty printing of results.
--quiet
    set log level to logging.CRITICAL (minimize logging output)
--no-color-info
    Disable using colors for info related things.
--color-info
    IPython can display information about objects via a set of functions,
    and optionally can use colors for this, syntax highlighting
    source code and various other elements. This is on by default, but can cause
    problems with some pagers. If you see such problems, you can disable the
    colours.
--init
    Initialize profile with default config files.  This is equivalent
    to running `ipython profile create <profile>` prior to startup.
--no-pdb
    Disable auto calling the pdb debugger after every exception.
--debug
    set log level to logging.DEBUG (maximize logging output)
--pydb
    Use the third party 'pydb' package as debugger, instead of pdb.
    Requires that pydb is installed.
--pdb
    Enable auto calling the pdb debugger after every exception.
--no-pprint
    Disable auto pretty printing of results.
--no-stderr
    redirect stderr to the null device
Traceback (most recent call last):
  File "//anaconda/envs/kaggle/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "//anaconda/envs/kaggle/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/anaconda/envs/kaggle/lib/python2.7/site-packages/octave_kernel.py", line 175, in <module>
    IPKernelApp.launch_instance(kernel_class=OctaveKernel)
  File "//anaconda/envs/kaggle/lib/python2.7/site-packages/traitlets/config/application.py", line 590, in launch_instance
    app = cls.instance(**kwargs)
  File "//anaconda/envs/kaggle/lib/python2.7/site-packages/traitlets/config/configurable.py", line 380, in instance
    inst = cls(*args, **kwargs)
  File "<decorator-gen-6>", line 2, in __init__
  File "//anaconda/envs/kaggle/lib/python2.7/site-packages/traitlets/config/application.py", line 77, in catch_config_error
    app.print_help()
  File "//anaconda/envs/kaggle/lib/python2.7/site-packages/traitlets/config/application.py", line 349, in print_help
    self.print_options()
  File "//anaconda/envs/kaggle/lib/python2.7/site-packages/traitlets/config/application.py", line 320, in print_options
    self.print_alias_help()
  File "//anaconda/envs/kaggle/lib/python2.7/site-packages/traitlets/config/application.py", line 284, in print_alias_help
    cls = classdict[classname]
KeyError: 'BaseIPythonApplication'

```

I have my `OCTAVE_EXECUTABLE=/usr/local/bin/octave`

Any ideas?

**Comment by blink1073** [comment]
Hi @brianbaquiran, sorry for the delay.  That looks like you have conflicting versions of the jupyter packages.  Can you try `conda install jupyter` and try again?

**Comment by brianbaquiran** [comment]
Hi @blink1073 , running `conda install jupyter` seems to have fixed the problem. I'm now able to create a notebook using the Octave kernel. 

Thanks!

**Comment by blink1073** [comment]
Great, cheers!
