### ISSUE TITLE
unexpected keyword argument 'parent'

### ISSUE THREAD

**Issue by rubensa** [Calysto/octave_kernel#222]
I can't get the octave_kernel up and run.
This is the error I get:
```bash
$ python -m octave_kernel.check
Octave kernel v0.34.2
Metakernel v0.29.2
Python v3.9.14 | packaged by conda-forge | (main, Nov 21 2022, 13:19:30) 
[GCC 10.4.0]
Python path: /opt/conda/envs/dev/bin/python

Connecting to Octave...
__init__() got an unexpected keyword argument 'parent'
```

Could you, please, help me on this?

**Comment by rubensa** [comment]
```bash
$ octave -v
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
GNU Octave, version 7.2.0
Copyright (C) 1993-2022 The Octave Project Developers.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-conda-linux-gnu".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
```

**Comment by rubensa** [comment]
This is how the environment was set under Ubuntu Linux 22.04:
```bash
conda create -y -n dev python=3.9
conda install -y -n dev -c conda-forge octave
conda install -y -n dev conda-build pylint autopep8
conda activate dev
pip install jupyter
pip install octave_kernel
```

**Comment by rubensa** [comment]
This is the error log trying to run a **jupyter** book under **VSCode** (in case it can help to trace the problem):
```bash
TypeError: __init__() got an unexpected keyword argument 'parent'... View Jupyter [log](command:jupyter.viewOutput) for further details.
	at ChildProcess.<anonymous> (/home/user/.vscode-server/extensions/ms-toolsai.jupyter-2022.9.1303220346/out/extension.node.js:2:2195101)
	at ChildProcess.emit (node:events:538:35)
	at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)] {
  category: 'kerneldied',
  kernelConnectionMetadata: {
    kind: 'startUsingLocalKernelSpec',
    kernelSpec: {
      specFile: '/opt/conda/envs/dev/share/jupyter/kernels/octave/kernel.json',
      interpreterPath: '/opt/conda/envs/dev/bin/python',
      isRegisteredByVSC: 'registeredByNewVersionOfExtForCustomKernelSpec',
      name: 'python3914jvsc74a57bd062e67a83eca6e542ae263c60cec4f6dec4cbb93237356f2037b8454ca6367d8b',
      argv: [Array],
      language: 'octave',
      executable: 'python',
      display_name: 'Octave',
      metadata: [Object]
    },
    id: '.jvsc74a57bd062e67a83eca6e542ae263c60cec4f6dec4cbb93237356f2037b8454ca6367d8b#octave./opt/conda/envs/dev/python./.python#-m#octave_kernel#-f#{connection_file}'
  },
  exitCode: 1,
  stdErr: 'Traceback (most recent call last):\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/runpy.py", line 197, in _run_module_as_main\n' +
    '    return _run_code(code, main_globals, None,\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/runpy.py", line 87, in _run_code\n' +
    '    exec(code, run_globals)\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/octave_kernel/__main__.py", line 5, in <module>\n' +
    '    OctaveKernel.run_as_main()\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/metakernel/_metakernel.py", line 122, in run_as_main\n' +
    '    MetaKernelApp.launch_instance(kernel_class=cls, *args, **kwargs)\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/metakernel/_metakernel.py", line 847, in launch_instance\n' +
    '    super(MetaKernelApp, cls).launch_instance(*args, **kwargs)\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/traitlets/config/application.py", line 981, in launch_instance\n' +
    '    app.initialize(argv)\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/traitlets/config/application.py", line 110, in inner\n' +
    '    return method(app, *args, **kwargs)\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 681, in initialize\n' +
    '    self.init_kernel()\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/ipykernel/kernelapp.py", line 528, in init_kernel\n' +
    '    kernel = kernel_factory(\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/traitlets/config/configurable.py", line 551, in instance\n' +
    '    inst = cls(*args, **kwargs)\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/metakernel/process_metakernel.py", line 53, in __init__\n' +
    '    MetaKernel.__init__(self, *args, **kwargs)\n' +
    '  File "/opt/conda/envs/dev/lib/python3.9/site-packages/metakernel/_metakernel.py", line 155, in __init__\n' +
    '    self.comm_manager = CommManager(**kwargs)\n' +
    "TypeError: __init__() got an unexpected keyword argument 'parent'\n"
}
```

**Comment by rubensa** [comment]
If I change the way to install **octave** and use the **Ubuntu package** (vs the **conda** version):
```bash
sudo apt-get -y install octave
```
it work.
```bash
$ python -m octave_kernel.check
Octave kernel v0.34.2
Metakernel v0.29.2
Python v3.9.15 (main, Nov  4 2022, 16:13:54) 
[GCC 11.2.0]
Python path: /opt/conda/envs/dev/bin/python

Connecting to Octave...
Octave connection established
Octave Kernel v0.34.2 running GNU Octave v5.2.0
Graphics toolkit: gnuplot
Available toolkits: 
  [1,1] = gnuplot
}
```
but the octave version is much older (5.2.0 vs 7.2.0):
```bash
$ octave -v
octave: X11 DISPLAY environment variable not set
octave: disabling GUI features
GNU Octave, version 5.2.0
Copyright (C) 2020 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-pc-linux-gnu".

Additional information about Octave is available at https://www.octave.org.

Please contribute if you find this software useful.
For more information, visit https://www.octave.org/get-involved.html

Read https://www.octave.org/bugs.html to learn how to submit bug reports.
```

**Comment by rubensa** [comment]
Just checked again with the **octave** **conda** install but setting the **octave** version to **6.4.0** and to **7.1.0**.  This time it worked with both versions so pretty much looks like incompatibility problem with **octave** version **7.2.0**.

**Comment by rubensa** [comment]
This is really weird...  If I explicitly set the **conda** version to **7.2.0** it works now... I can't understand anything...

_NOTE_:  All my tries where made in Docker containers so my tries should be reproducible but looks like they are not as I had a not working environment that now is a working environment.

**Comment by rubensa** [comment]
I don't know why but it is working now.  So I close this.

**Comment by blink1073** [comment]
Hi @rubensa, I believe this was caused by ipykernel 6.18.0, which I released and then yanked yesterday.

**Comment by rubensa** [comment]
Oh!!  Thanks for the info @blink1073...  I was like crazy trying to find out what was the problem.

**Comment by rubensa** [comment]
For reference (anyone interested), see: https://github.com/ipython/ipykernel/issues/1026
