### ISSUE TITLE
Error when running plot magic before any command

### ISSUE THREAD

**Issue by knuesel** [Calysto/octave_kernel#224]
Starting the first cell with a plot magic gives the following error:

```
Error in calling magic 'plot' on line:
    'OctaveEngine' object has no attribute '_default_toolkit'
    args: []
    kwargs: {'height': None, 'width': None, 'resolution': None, 'backend': 'inline', 'format': 'pdf', 'size': None}
Traceback (most recent call last):
  File "/home/j/.local/lib/python3.10/site-packages/metakernel/magic.py", line 96, in call_magic
    func(*args, **kwargs)
  File "/home/j/.local/lib/python3.10/site-packages/metakernel/magics/plot_magic.py", line 58, in line_plot
    self.kernel.handle_plot_settings()
  File "/home/j/.local/lib/python3.10/site-packages/octave_kernel/kernel.py", line 162, in handle_plot_settings
    self.octave_engine.plot_settings = self.plot_settings
  File "/home/j/.local/lib/python3.10/site-packages/octave_kernel/kernel.py", line 219, in plot_settings
    default_inline_toolkit = self.inline_toolkit or self._default_toolkit
AttributeError: 'OctaveEngine' object has no attribute '_default_toolkit'
```

A quick fix is to add

```
if not self._has_startup:
  self._default_toolkit = self.eval('graphics_toolkit', silent=True).split()[-1]
```

at the beginning of the `plot_settings` function but maybe you want a cleaner solution...

**Comment by blink1073** [comment]
Your fix sounds good to me, would you like to submit a PR?
