### ISSUE TITLE
[Windows 11] TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Polda18** [Calysto/octave_kernel#230]
Hello. I'm not sure if something is wrong in my configuration, or something got corrupted. I got the latest version of Jupyter, and the latest version of Octave Kernel, as well as the latest version of Octave itself. My friend has the exact same configuration as me. The difference is his config works, mine does not.

This is what Jupyter server console prints out every time I open an Octave Notebook:
```
[MetaKernelApp] ERROR | Exception in control handler:
Traceback (most recent call last):
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 337, in process_control
    await result
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 864, in kernel_info_request
    content.update(self.kernel_info)
                   ^^^^^^^^^^^^^^^^
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ipykernel\kernelbase.py", line 856, in kernel_info
    "language_info": self.language_info,
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\octave_kernel\kernel.py", line 87, in language_info
    'version': self.language_version,
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\octave_kernel\kernel.py", line 78, in language_version
    ver = self.octave_engine.eval('version', silent=True)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\octave_kernel\kernel.py", line 99, in octave_engine
    self._octave_engine = OctaveEngine(plot_settings=self.plot_settings,
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\octave_kernel\kernel.py", line 182, in __init__
    self.executable = self._get_executable()
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marpo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\octave_kernel\kernel.py", line 479, in _get_executable
    if 'snap' not in fullpath:
       ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

Even simplest math expression fails to execute, nothing really works. Setting up a config file in Jupyter config does nothing, and I'm not sure what's wrong. This is the contents of `octave_kernel_config.py` file in Jupyter config dir:
```py
# use Qt as the default backend for plots
c.OctaveKernel.plot_settings = dict(backend='qt')
```
I directly copied it from the kernel websites. Not sure what should I even do there. All I want is to just get it to work.

I've set up `%PATH%` and `%OCTAVE_EXECUTABLE%` environment variables to include the Octave installation dir and executable file. I don't know what else to do to get it working.

**Comment by Polda18** [comment]
Quick heads up. I did a diff check on kernel installation of mine and my friend's, even compared checksums, and came into conclusion we have identical version. However, he has Python 3.10 and I have 3.11, could the newer version of Python cause issues?

**Comment by blink1073** [comment]
It looks like `which` isn't finding your executable.  You can test this out locally:

```
import os
from metakernel.pexpect import which
print(which(os.environ['OCTAVE_EXECUTABLE']))
```

**Comment by Polda18** [comment]
It could be that I didn't set up system environment variable, I set up user environment variable. What's even stranger is that my friend didn't even set up `OCTAVE_EXECUTABLE` and it works for him. The only thing he did was including its installation dir in `PATH`. I guess there are differences between versions of Windows.

**Comment by Polda18** [comment]
It seems that Python doesn't have access to the `OCTAVE_EXECUTABLE`:
```
C:\Users\marpo>python
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> from metakernel.pexpect import which
0.02s - Debugger warning: It seems that frozen modules are being used, which may
0.00s - make the debugger miss breakpoints. Please pass -Xfrozen_modules=off
0.00s - to python to disable frozen modules.
0.00s - Note: Debugging will proceed. Set PYDEVD_DISABLE_FILE_VALIDATION=1 to disable this validation.
>>> print(which(os.environ['OCTAVE_EXECUTABLE']))
None
```

**Comment by blink1073** [comment]
Great, I'm glad you unstuck!
