### ISSUE TITLE
Windows octave_kernel stopped working with latest update

### ISSUE THREAD

**Issue by profbrady** [Calysto/octave_kernel#33]
I have Jupyter running Octave on my Mac natively and in an Ubuntu 14.04 VM. A few days ago I had it running fine in a Windows 7 VM. It stopped working earlier today on Windows when I updated the Octave kernel. I uninstalled the kernel using `pip uninstall octave_kernel` then used `jupyter kernelspec list` to see what kernels were installed. I removed the octave kernel folders and ran the command again (below). Then I reinstalled the octave kernel. However, Octave commands still won't run on Windows. I need to get this fixed, I am going to have students install Jupyter and Octave to use in class starting 4 days from now. I thought I had it covered until today.

```
[Anaconda3] C:\Users\bradyb>jupyter kernelspec list
Available kernels:
  python3    C:\Anaconda3\lib\site-packages\ipykernel\resources

[Anaconda3] C:\Users\bradyb>pip install octave_kernel
Collecting octave-kernel
  Using cached octave_kernel-0.15.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): metakernel>=0.10.5 in c:\anaconda3\lib\site-packages (from octave-kernel)
Requirement already satisfied (use --upgrade to upgrade): IPython>=3.0 in c:\anaconda3\lib\site-packages (from metakernel>=0.10.5->octave-kernel)
Installing collected packages: octave-kernel
Successfully installed octave-kernel-0.15.1

[Anaconda3] C:\Users\bradyb>python -m octave_kernel.install

[Anaconda3] C:\Users\bradyb>jupyter notebook
[I 00:32:29.695 NotebookApp] Serving notebooks from local directory: C:\Users\bradyb
[I 00:32:29.695 NotebookApp] 0 active kernels
[I 00:32:29.695 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 00:32:29.695 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 00:32:38.025 NotebookApp] Kernel started: 3e0bc2b1-47d7-407f-832c-cd1a1250695c
[IPKernelApp] ERROR | Exception in message handler:
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 212, in dispatch_shell
    handler(stream, idents, msg)
  File "C:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 370, in execute_request
    user_expressions, allow_stdin)
  File "C:\Anaconda3\lib\site-packages\metakernel\_metakernel.py", line 337, in do_execute
    retval = self.do_execute_direct(code)
  File "C:\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 95, in do_execute_direct
    self.handle_plot_settings()
  File "C:\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 182, in handle_plot_settings
    self.do_execute_direct('\n'.join(cmds))
  File "C:\Anaconda3\lib\site-packages\octave_kernel\kernel.py", line 106, in do_execute_direct
    resp = super(OctaveKernel, self).do_execute_direct(code)
  File "C:\Anaconda3\lib\site-packages\metakernel\process_metakernel.py", line 61, in do_execute_direct
    output = self.wrapper.run_command(code.rstrip(), timeout=None)
  File "C:\Anaconda3\lib\site-packages\metakernel\replwrap.py", line 136, in run_command
    self._expect_prompt(timeout=timeout)
  File "C:\Anaconda3\lib\site-packages\metakernel\replwrap.py", line 101, in _expect_prompt
    timeout=timeout)
  File "C:\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1649, in expect
    timeout, searchwindowsize, async)
  File "C:\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1670, in expect_list
    return exp.expect_loop(timeout)
  File "C:\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 225, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "C:\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1084, in read_nonblocking
    return self._winread(size, timeout)
  File "C:\Anaconda3\lib\site-packages\metakernel\pexpect.py", line 1034, in _winread
    while (time.time() - t0) < timeout and len(buf) < size:
TypeError: unorderable types: float() < NoneType()
```

**Comment by blink1073** [comment]
Does making this change fix the problem?

```diff
--- a/metakernel/pexpect.py
+++ b/metakernel/pexpect.py
@@ -1031,6 +1031,10 @@ class spawn(object):
     def _winread(self, size, timeout):
         t0 = time.time()
         buf = ''
+        if timeout is None:
+            timeout = 30
+        elif timeout == -1:
+            timeout = 1e6
         while (time.time() - t0) < timeout and len(buf) < size:
             try:
                 incoming = self._read_queue.get_nowait()

**Comment by blink1073** [comment]
I just released a version of metakernel that should fix this.  `pip install -U metakernel`.

**Comment by profbrady** [comment]
Thanks for the quick reply and fix. I ran the update on all 3 systems and they all work. I now have Jupyter working with Octave on Mac OS X El Capitan, MS Windows 10 32 bit, and Ubuntu Linux 14.04. I should be covered for any OS my students throw at me on Thursday. I am closing the ticket.

**Comment by dsblank** [comment]
Thanks @profbrady for this, and the feedback! By the way, where are you using this? (I, too, am a prof, and wonder where others are using these tools.) I'm using Jupyterhub, which gives me a bit more control.

**Comment by profbrady** [comment]
@dsblank I teach Mechanical Engineering Technology at Ferris State University in Big Rapids, MI. I teach a Computer Applications for Technology in the Spring semesters that covers an introduction to programming for engineering technology students. I use Octave and Arduino. About 10 of 15 weeks are spent with Octave. This is the first semester that I am having students use Jupyter notebooks for command line work. They will still use the Octave GUI for writing scripts that require user input. I need to investigate Jupyterhub for next year. I am not up to snuff on the tasks necessary to set that up at this time.
