### ISSUE TITLE
Need MANIFEST.in listing README.rst

### ISSUE THREAD

**Issue by dsblank** [Calysto/octave_kernel#5]
I _think_ I have setup figured out; looks like you need to add a MANIFEST.in to the folder with the README.rst included in the MANIFEST.in:

```$ sudo -H pip install octave_kernel -U
Collecting octave-kernel
  Using cached octave_kernel-0.8.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-neQyg9/octave-kernel/setup.py", line 50, in <module>
        long_description=open('README.rst', 'r').read(),
    IOError: [Errno 2] No such file or directory: 'README.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-neQyg9/octave-kernel/setup.py", line 50, in <module>
    
        long_description=open('README.rst', 'r').read(),
    
    IOError: [Errno 2] No such file or directory: 'README.rst'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-neQyg9/octave-kernel
```

**Comment by blink1073** [comment]
Fixed, thanks!
