### ISSUE TITLE
Problem during installation, says `install_kernel_spec() got an unexpected keyword argument 'prefix'`

### ISSUE THREAD

**Issue by abangfarhan** [Calysto/octave_kernel#56]
I have not found this problem anywhere. After installing the kernel using `pip install octave_kernel` on my command prompt, I typed in `python -m octave_kernel.install` and got this:

```
C:\WINDOWS\system32>python -m octave_kernel.install
Traceback (most recent call last):
  File "D:\Users\USER\Anaconda3\lib\site-packages\octave_kernel\install.py", line 30, in install_my_kernel_spec
    replace=True, prefix=prefix)
TypeError: install_kernel_spec() got an unexpected keyword argument 'prefix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\USER\Anaconda3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Users\USER\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\USER\Anaconda3\lib\site-packages\octave_kernel\install.py", line 59, in <module>
    main(argv=sys.argv)
  File "D:\Users\USER\Anaconda3\lib\site-packages\octave_kernel\install.py", line 55, in main
    install_my_kernel_spec(user=user, prefix=prefix)
  File "D:\Users\USER\Anaconda3\lib\site-packages\octave_kernel\install.py", line 33, in install_my_kernel_spec
    replace=True, prefix=prefix)
TypeError: install_kernel_spec() got an unexpected keyword argument 'prefix'
```

I am using Windows 10 and have installed the Octave.

**Comment by blink1073** [comment]
Hi @abangfarhan, sorry, it looks like this was added in `jupyter_client` 4.3: https://github.com/jupyter/jupyter_client/pull/160.  Please `pip install -U jupyter_client` and I'll update the dependency.

**Comment by blink1073** [comment]
Closing as addressed, please feel free to reopen if the above foes not work.
