### ISSUE TITLE
unable to install octave in OSX Sierra

### ISSUE THREAD

**Issue by smartinsightsfromdata** [Calysto/octave_kernel#87]
I'm following the instructions:

* I install octave with home-brew.
* octave works at the command line (opening the gun etc.).
* I install octave_kernel with pip

After the pip command I get:
```
Successfully installed octave-kernel-0.26.2
```
But octave do not appear in the list of kernels (I have scala, python3, etc.
I run `jupyter console --kernel octave` :

```
$ jupyter console --kernel octave
Traceback (most recent call last):
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 201, in get_kernel_spec
    resource_dir = d[kernel_name.lower()]
KeyError: 'octave'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/e/anaconda3/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-114>", line 2, in initialize
  File "/Users/e/anaconda3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 141, in initialize
    self.init_shell()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_console/app.py", line 109, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 244, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 175, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_client/manager.py", line 87, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/Users/e/anaconda3/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 203, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named octave
```

This is the output of `jupyter kernelspec list`:

```
Available kernels:
  aimlbot      /Users/e/Library/Jupyter/kernels/aimlbot
  ir           /Users/e/Library/Jupyter/kernels/ir
  julia-0.5    /Users/e/Library/Jupyter/kernels/julia-0.5
  scala        /Users/e/Library/Jupyter/kernels/scala
  python3      /Users/e/anaconda3/share/jupyter/kernels/python3
```

No octave...

**Comment by smartinsightsfromdata** [comment]
I just realised I didn't run it first:
`python -m octave_kernel.install`

Now it works.

**Comment by dsblank** [comment]
Thanks for the update, and good luck computing!
