### ISSUE TITLE
Kernel dead: No module named metakernel on Ubuntu 16.04 64bit

### ISSUE THREAD

**Issue by ysh329** [Calysto/octave_kernel#88]
jupyter notebook messages as below:
```Shell
[I 11:31:00.467 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 74467248-be76-4482-9a95-29d127e68299 restarted
Traceback (most recent call last):
  File "/usr/local/lib/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/yuens/Downloads/code/octave_kernel/octave_kernel/__main__.py", line 2, in <module>
    from .kernel import OctaveKernel
  File "octave_kernel/kernel.py", line 14, in <module>
    from metakernel import MetaKernel, ProcessMetaKernel, REPLWrapper, u
ImportError: No module named metakernel
```

**Comment by dsblank** [comment]
metakernel is listed as a requirement in the setup.py, so something must have happened when you installed octave_kernel. How did you install it?

You might be able to fix this by installing it directly, like:

```
pip install metakernel
```

**Comment by ysh329** [comment]
@dsblank I have executed this `sudo -H pip install metakernel`:
```Shell
yuens@Spark:~$ sudo -H pip install metakernel
[sudo] password for yuens: 
Requirement already satisfied: metakernel in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: ipykernel in /usr/local/lib/python2.7/dist-packages (from metakernel)
Requirement already satisfied: pexpect>=4.2 in /usr/local/lib/python2.7/dist-packages (from metakernel)
Requirement already satisfied: ipython>=4.0.0 in /usr/local/lib/python2.7/dist-packages (from ipykernel->metakernel)
Requirement already satisfied: traitlets>=4.1.0 in /usr/local/lib/python2.7/dist-packages (from ipykernel->metakernel)
Requirement already satisfied: tornado>=4.0 in /usr/local/lib/python2.7/dist-packages (from ipykernel->metakernel)
Requirement already satisfied: jupyter-client in /usr/local/lib/python2.7/dist-packages (from ipykernel->metakernel)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python2.7/dist-packages (from pexpect>=4.2->metakernel)
Requirement already satisfied: pickleshare in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: simplegeneric>0.8 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: backports.shutil-get-terminal-size; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: decorator in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: pygments in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: pathlib2; python_version == "2.7" or python_version == "3.3" in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: prompt-toolkit<2.0.0,>=1.0.4 in /usr/local/lib/python2.7/dist-packages (from ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: enum34; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.1.0->ipykernel->metakernel)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.1.0->ipykernel->metakernel)
Requirement already satisfied: ipython-genutils in /usr/local/lib/python2.7/dist-packages (from traitlets>=4.1.0->ipykernel->metakernel)
Requirement already satisfied: singledispatch in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel->metakernel)
Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel->metakernel)
Requirement already satisfied: backports-abc>=0.4 in /usr/local/lib/python2.7/dist-packages (from tornado>=4.0->ipykernel->metakernel)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel->metakernel)
Requirement already satisfied: pyzmq>=13 in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel->metakernel)
Requirement already satisfied: jupyter-core in /usr/local/lib/python2.7/dist-packages (from jupyter-client->ipykernel->metakernel)
Requirement already satisfied: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2; python_version == "2.7" or python_version == "3.3"->ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: appdirs>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from setuptools>=18.5->ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: packaging>=16.8 in /usr/local/lib/python2.7/dist-packages (from setuptools>=18.5->ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: wcwidth in /usr/local/lib/python2.7/dist-packages (from prompt-toolkit<2.0.0,>=1.0.4->ipython>=4.0.0->ipykernel->metakernel)
Requirement already satisfied: pyparsing in /usr/local/lib/python2.7/dist-packages (from packaging>=16.8->setuptools>=18.5->ipython>=4.0.0->ipykernel->metakernel)
```

After `sudo -H pip install metakernel`, I created an Octave kernel. However, terminal shows below Jupyter Logs and **Kernel dead**( It shows No kernel in Jupyter Notebook GUI):

```Shell
[I 19:21:04.212 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[I 19:21:08.694 NotebookApp] Creating new notebook in 
[I 19:21:09.770 NotebookApp] Kernel started: df80c2a9-8b57-4d9d-a4dd-379b9f4b8930
/usr/local/lib/anaconda2/bin/python: No module named octave_kernel
[I 19:21:12.769 NotebookApp] KernelRestarter: restarting kernel (1/5)
/usr/local/lib/anaconda2/bin/python: No module named octave_kernel
[I 19:21:15.775 NotebookApp] KernelRestarter: restarting kernel (2/5)
/usr/local/lib/anaconda2/bin/python: No module named octave_kernel
[I 19:21:18.780 NotebookApp] KernelRestarter: restarting kernel (3/5)
/usr/local/lib/anaconda2/bin/python: No module named octave_kernel
[W 19:21:19.834 NotebookApp] Timeout waiting for kernel_info reply from df80c2a9-8b57-4d9d-a4dd-379b9f4b8930
[I 19:21:21.786 NotebookApp] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel df80c2a9-8b57-4d9d-a4dd-379b9f4b8930 restarted
/usr/local/lib/anaconda2/bin/python: No module named octave_kernel
[W 19:21:24.791 NotebookApp] KernelRestarter: restart failed
[W 19:21:24.791 NotebookApp] Kernel df80c2a9-8b57-4d9d-a4dd-379b9f4b8930 died, removing from map.
ERROR:root:kernel df80c2a9-8b57-4d9d-a4dd-379b9f4b8930 restarted failed!
[W 19:21:24.815 NotebookApp] Kernel deleted before session
[W 19:21:24.816 NotebookApp] 410 DELETE /api/sessions/2256a530-c02e-4709-8cdc-2cc2f1d1453a (127.0.0.1) 2.70ms referer=http://localhost:8889/notebooks/Untitled.ipynb?kernel_name=octave
```

**Comment by dsblank** [comment]
How did you install ocatve_kernel? It looks like pip is installing in python2.7 folders where jupyter may be associated with a different python, or with a python env.

**Comment by ysh329** [comment]
@dsblank 
I use python2.7 provided by Anaconda-python-2.7-64-bit, not python env.
I installed according to README.md:
```Shell
sudo -H pip install octave_kernel
python -m octave_kernel.install
```
First, install octave_kernel as usual, print a lot logs.
Second, I ran `python -m octave_kernel.install` in `~/Downloads/code/octave_kernel` directory, but it didn't print any logs, is it abnormal?

**Comment by dsblank** [comment]
Perhaps your pip is out of date? You might try:

```
sudo -H pip install pip --update
```

**Comment by ysh329** [comment]
@dsblank 
pip 9.0.1 from /usr/local/lib/anaconda2/lib/python2.7/site-packages (python 2.7)

**Comment by blink1073** [comment]
@ysh329, sorry I missed this one.  The issue is that you're using two different paths.  The following would help diagnose:

```
which python
which pip
which jupyter
jupyter kernelspec list
# cat the kernel.json file in the octave kernel path shown in the previous step
```

**Comment by ysh329** [comment]
@blink1073 Thanks
