### ISSUE TITLE
OSError: Octave Executable not found

### ISSUE THREAD

**Issue by FengLi666** [Calysto/octave_kernel#89]
On Ubuntu 16.06 64bit
~~~python
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/octave_kernel/__main__.py", line 3, in <module>
    IPKernelApp.launch_instance(kernel_class=OctaveKernel)
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-121>", line 2, in initialize
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 457, in initialize
    self.init_kernel()
  File "/usr/local/lib/python3.5/dist-packages/ipykernel/kernelapp.py", line 368, in init_kernel
    user_ns=self.user_ns,
  File "/usr/local/lib/python3.5/dist-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/metakernel/process_metakernel.py", line 54, in __init__
    self.wrapper = self.makeWrapper()
  File "/usr/local/lib/python3.5/dist-packages/octave_kernel/kernel.py", line 80, in makeWrapper
    return self.octave_engine.repl
  File "/usr/local/lib/python3.5/dist-packages/octave_kernel/kernel.py", line 74, in octave_engine
    logger=self.log)
  File "/usr/local/lib/python3.5/dist-packages/octave_kernel/kernel.py", line 143, in __init__
    self.executable = self._get_executable()
  File "/usr/local/lib/python3.5/dist-packages/octave_kernel/kernel.py", line 417, in _get_executable
    raise OSError(msg)
OSError: Octave Executable not found, please add to path or set"OCTAVE_EXECUTABLE" environment variable
~~~
Where can i find the Octave Executable ?

**Comment by blink1073** [comment]
Hi @FengLi666, Octave itself has to be installed separately, here are some instructions to get the latest stable release: https://www.scivision.co/latest-octave-on-ubuntu-ppa/.

**Comment by FengLi666** [comment]
Thank you @blink1073
