### ISSUE TITLE
RuntimeError on Windows 10 

### ISSUE THREAD

**Issue by Suraj-Yadav** [Calysto/octave_kernel#90]
Hi
I installed octave_kernel and have set up the environment as given in README. But when i run the command `jupyter console --kernel octave`, it fails giving a run time error.
Here is the output of `jupyter console --kernel octave --debug`
```
[ZMQTerminalIPythonApp] Searching ['C:\\Users\\Suraj', 'C:\\Users\\Suraj\\.jupyter', 'g:\\program files\\python36\\etc\\jupyter', 'C:\\ProgramData\\jupyter'] for config files
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\ProgramData\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in g:\program files\python36\etc\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\Users\Suraj\.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_config in C:\Users\Suraj
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\ProgramData\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in g:\program files\python36\etc\jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\Users\Suraj\.jupyter
[ZMQTerminalIPythonApp] Looking for jupyter_console_config in C:\Users\Suraj
[ZMQTerminalIPythonApp] Connection File not found: C:\Users\Suraj\AppData\Roaming\jupyter\runtime\kernel-12904.json
[ZMQTerminalIPythonApp] Found kernel octave in C:\Users\Suraj\AppData\Roaming\jupyter\kernels
[ZMQTerminalIPythonApp] Found kernel python3 in g:\program files\python36\share\jupyter\kernels
[ZMQTerminalIPythonApp] Starting kernel: ['G:\\Program Files\\Python36\\python.exe', '-m', 'octave_kernel', '-f', 'C:\\Users\\Suraj\\AppData\\Roaming\\jupyter\\runtime\\kernel-12904.json']
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:3053
[ZMQTerminalIPythonApp] connecting shell channel to tcp://127.0.0.1:3050
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:3050
[ZMQTerminalIPythonApp] connecting iopub channel to tcp://127.0.0.1:3051
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:3051
[ZMQTerminalIPythonApp] connecting stdin channel to tcp://127.0.0.1:3052
[ZMQTerminalIPythonApp] Connecting to: tcp://127.0.0.1:3052
[ZMQTerminalIPythonApp] connecting heartbeat channel to tcp://127.0.0.1:3054
Traceback (most recent call last):
  File "g:\program files\python36\lib\site-packages\jupyter_console\ptshell.py", line 321, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
  File "g:\program files\python36\lib\site-packages\jupyter_client\client.py", line 77, in get_shell_msg
    return self.shell_channel.get_msg(*args, **kwargs)
  File "g:\program files\python36\lib\site-packages\jupyter_client\blocking\channels.py", line 57, in get_msg
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "g:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "g:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "G:\Program Files\Python36\Scripts\jupyter-console.EXE\__main__.py", line 9, in <module>
  File "g:\program files\python36\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "g:\program files\python36\lib\site-packages\traitlets\config\application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-115>", line 2, in initialize
  File "g:\program files\python36\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "g:\program files\python36\lib\site-packages\jupyter_console\app.py", line 141, in initialize
    self.init_shell()
  File "g:\program files\python36\lib\site-packages\jupyter_console\app.py", line 114, in init_shell
    client=self.kernel_client,
  File "g:\program files\python36\lib\site-packages\traitlets\config\configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
  File "g:\program files\python36\lib\site-packages\jupyter_console\ptshell.py", line 270, in __init__
    self.init_kernel_info()
  File "g:\program files\python36\lib\site-packages\jupyter_console\ptshell.py", line 324, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request")
RuntimeError: Kernel didn't respond to kernel_info_request
```

My program versions are
```
=>python --version
Python 3.6.0

=>where pip
G:\Program Files\Python36\Scripts\pip.exe
=>pip --version
pip 9.0.1 from g:\program files\python36\lib\site-packages (python 3.6)

=>pip show octave_kernel
Name: octave-kernel
Version: 0.26.2
...

=>octave --version
GNU Octave, version 4.2.1
...

=>echo %OCTAVE_EXECUTABLE%
C:\ExtLibs\Octave-4.2.1\bin\octave.exe
```

Also if i run `jupyter notebook`, i can create a notebook with 'Octave' in New menu, but nothing happens when i run any command.

Has anyone seen this before?

**Comment by dsblank** [comment]
Any chance that you can test with Python 3.5?

**Comment by Suraj-Yadav** [comment]
Yes, it is working with Python 3.5.2.

**Comment by blink1073** [comment]
Seems that way.  We have been [testing](https://github.com/Calysto/octave_kernel/blob/7399120bfbeaeccf02b30b3a6b68aa7928b4170d/.travis.yml#L3-L4) against 3.5 and 3.6, and I use 3.5 locally.

**Comment by blink1073** [comment]
(Updating the above comment with the correct versions).

**Comment by dsblank** [comment]
Getting some Travis errors on hash mismatches on https://github.com/Calysto/octave_kernel/pull/91 ... any ideas?

**Comment by blink1073** [comment]
Hmm, I restarted an old passing build and got the same problem.  Maybe the ppa needs to be updated?  https://travis-ci.org/Calysto/octave_kernel/jobs/211264474

**Comment by blink1073** [comment]
Or perhaps it is time to update to a `trusty` build.

**Comment by blink1073** [comment]
It isn't Python 3.6 in general, because #92 is passing on Travis, so I'm not entirely sure why it would fail on Windows.
